name: tests unitaires

on: [push]

jobs:
  test1:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pytest
        run: python -m pip install pytest

      - name: Display branch
        run: 'echo "Nom branche: ${{ github.ref }}"'

      - name: Display OS
        run: 'echo "OS: ${{ runner.os }}"'

      - name: Display Python version
        run: python --version

      - name: Run tests
        run: python -m pytest TP1/test.py
