name: tests unitaires

on: [push]

jobs:
  test1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python for Demo
        uses: actions/setup-python@v4

      - name: Install pytest
        run: python3 -m pip install pytest

      - name: Display branch
        run: echo "Nom branche: ${{ github.ref }}"

      - name: Display OS
        run: echo "OS: ${{ runner.os }}"

      - name: Run tests
        run: cd TP1 && python3 -m pytest test.py

